// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD0yySVuWjvkIvf9hJcUDBHd1SQYHbBrg',
    appId: '1:316764829832:web:c6aa01eadc3514d914873d',
    messagingSenderId: '316764829832',
    projectId: 'flutterprojekt-fbb6e',
    authDomain: 'flutterprojekt-fbb6e.firebaseapp.com',
    storageBucket: 'flutterprojekt-fbb6e.firebasestorage.app',
    measurementId: 'G-S4QK61QX52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS9Z2rTPs6Vo_xM_cdMeiuuivPW-nMKDg',
    appId: '1:316764829832:android:ca1a81c14ceee3a114873d',
    messagingSenderId: '316764829832',
    projectId: 'flutterprojekt-fbb6e',
    storageBucket: 'flutterprojekt-fbb6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQpvsWreMcUMpukEQ5101onR7m7dOj2oY',
    appId: '1:316764829832:ios:7c1b8abcbd426f1e14873d',
    messagingSenderId: '316764829832',
    projectId: 'flutterprojekt-fbb6e',
    storageBucket: 'flutterprojekt-fbb6e.firebasestorage.app',
    iosBundleId: 'com.example.vaja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQpvsWreMcUMpukEQ5101onR7m7dOj2oY',
    appId: '1:316764829832:ios:7c1b8abcbd426f1e14873d',
    messagingSenderId: '316764829832',
    projectId: 'flutterprojekt-fbb6e',
    storageBucket: 'flutterprojekt-fbb6e.firebasestorage.app',
    iosBundleId: 'com.example.vaja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD0yySVuWjvkIvf9hJcUDBHd1SQYHbBrg',
    appId: '1:316764829832:web:9020b9fe1deba99f14873d',
    messagingSenderId: '316764829832',
    projectId: 'flutterprojekt-fbb6e',
    authDomain: 'flutterprojekt-fbb6e.firebaseapp.com',
    storageBucket: 'flutterprojekt-fbb6e.firebasestorage.app',
    measurementId: 'G-VKRX3ZWSZV',
  );
}
